### ISSUE TITLE
Decompose this Terraform module

### ISSUE THREAD

**Issue by jsf9k** [cisagov/molecule-packer-ci-iam-user-tf-module#10]
# 🚀 Feature Proposal

This module is trying to serve both molecule and packer and has gotten too big and complicated.  It should be decomposed.

## Motivation

For testing Ansible role repositories using molecule via CI, we want to create roles that simply read one or more SSM Parameter Store parameters.  With the current code, you will have to provide a provider that doesn't get used if you specify `var.add_packer_permissions = false`.  This is ugly and troubles me greatly.

I'm thinking that maybe this module is doing too much, and perhaps we need to decompose it into:
* A module that creates a policy for reading specified SSM Parameter Store parameters
* A module that leverages the previous module and goes on to create a user that can assume the role.  This module is useful for testing molecule repositories via CI.
* This module, which leverages the first module but also creates the AMI creation policy, a role with both policies attached, and a user that can assume that role.

## Example

As I said above, this feature would be used for testing Ansible role repositories using molecule via CI.

## Pitch

The content above should be pitch enough.

**Comment by dav3r** [comment]
Here's what I'm thinking for names of each new module:

> * A module that creates a policy for reading specified SSM Parameter Store parameters

I think we can use this existing module: https://github.com/cisagov/ssm-read-role-tf-module

> * A module that leverages the previous module and goes on to create a user that can assume the role.  This module is useful for testing molecule repositories via CI.

`molecule-iam-user-tf-module`

> * This module, which leverages the first module but also creates the AMI creation policy, a role with both policies attached, and a user that can assume that role.

`ami-build-iam-user-module`

@jsf9k, does this work for you?

**Comment by dav3r** [comment]
This issue has been resolved via:

- https://github.com/cisagov/ssm-read-role-tf-module/pull/2
- Creation of [`molecule-iam-user-tf-module`](https://github.com/cisagov/molecule-iam-user-tf-module)
- Creation of [`ami-build-iam-user-tf-module`](https://github.com/cisagov/ami-build-iam-user-tf-module)
